name: Daily Meritech Scraper

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install system dependencies for Selenium
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Run scraper
        run: python download.py

      - name: Commit results
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add data/*.csv
          git add plots/*.png || true  # if any
          git commit -m "Daily update for $(date +'%Y-%m-%d')" || echo "Nothing to commit"
          git push